'use client'
import { createContext, useContext, useState, useEffect } from 'react'

// ── Telugu translations ──────────────────────────────────────────────────────
const te = {
  appName: 'KRUTHIK FARM',
  tagline: 'పొలం నుండి నేరుగా మీకు',
  loading: 'లోడవుతోంది...',
  login: 'లాగిన్',
  logout: 'లాగ్ అవుట్',
  phone: 'ఫోన్ నంబర్',
  password: 'పాస్‌వర్డ్',
  loginBtn: 'లాగిన్ చేయి',
  loggingIn: 'లాగిన్ అవుతోంది...',
  dashboard: 'డాష్‌బోర్డ్',
  products: 'ఉత్పత్తులు',
  animals: 'పశువులు',
  orders: 'ఆర్డర్లు',
  customers: 'కస్టమర్లు',
  employees: 'ఉద్యోగులు',
  inventory: 'స్టాక్',
  categories: 'వర్గాలు',
  catalog: 'కేటలాగ్',
  publicCatalog: 'పబ్లిక్ కేటలాగ్',
  search: 'వెతుకు...',
  add: 'జోడించు',
  edit: 'సవరించు',
  delete: 'తొలగించు',
  save: 'సేవ్ చేయి',
  cancel: 'రద్దు చేయి',
  confirm: 'నిర్ధారించు',
  close: 'మూసివేయి',
  back: '← వెనక్కి',
  name: 'పేరు',
  nameTelugu: 'పేరు (తెలుగు)',
  price: 'ధర',
  stock: 'స్టాక్',
  minStock: 'కనీస స్టాక్',
  unit: 'యూనిట్',
  description: 'వివరణ',
  category: 'వర్గం',
  subcategory: 'ఉప వర్గం',
  photo: 'ఫోటో',
  status: 'స్థితి',
  available: 'అందుబాటులో',
  unavailable: 'అందుబాటులో లేదు',
  totalProducts: 'మొత్తం ఉత్పత్తులు',
  availableProducts: 'అందుబాటు ఉత్పత్తులు',
  totalOrders: 'మొత్తం ఆర్డర్లు',
  completedOrders: 'పూర్తయిన ఆర్డర్లు',
  totalCustomers: 'మొత్తం కస్టమర్లు',
  totalEmployees: 'మొత్తం ఉద్యోగులు',
  inventoryValue: 'స్టాక్ విలువ',
  totalRevenue: 'మొత్తం ఆదాయం',
  pendingPayments: 'పెండింగ్ చెల్లింపులు',
  recentOrders: 'తాజా ఆర్డర్లు',
  lowStock: 'తక్కువ స్టాక్',
  quickActions: 'త్వరిత చర్యలు',
  farmSummary: 'ఫారం సారాంశం',
  pending: 'పెండింగ్',
  confirmed: 'నిర్ధారించబడింది',
  completed: 'పూర్తయింది',
  cancelled: 'రద్దు చేయబడింది',
  all: 'అన్నీ',
  noProducts: 'ఉత్పత్తులు లేవు',
  noOrders: 'ఆర్డర్లు లేవు',
  noCustomers: 'కస్టమర్లు లేవు',
  noAnimals: 'పశువులు లేవు',
  addProduct: 'ఉత్పత్తి జోడించు',
  editProduct: 'ఉత్పత్తి సవరించు',
  deleteProduct: 'ఉత్పత్తి తొలగించు',
  addCategory: 'వర్గం జోడించు',
  addEmployee: 'ఉద్యోగి జోడించు',
  addCustomer: 'కస్టమర్ జోడించు',
  addAnimal: 'పశువు జోడించు',
  addOrder: 'ఆర్డర్ జోడించు',
  totalAmount: 'మొత్తం మొత్తం',
  paidAmount: 'చెల్లించిన మొత్తం',
  balance: 'బాకీ',
  customer: 'కస్టమర్',
  product: 'ఉత్పత్తి',
  quantity: 'పరిమాణం',
  address: 'చిరునామా',
  role: 'పాత్ర',
  owner: 'యజమాని',
  manager: 'మేనేజర్',
  employee: 'ఉద్యోగి',
  welcome: 'స్వాగతం',
  callUs: 'మాకు కాల్ చేయండి',
  whatsapp: 'వాట్సాప్‌లో ఆర్డర్ చేయండి',
  contactUs: 'మాకు సంప్రదించండి',
  shopByCategory: 'వర్గం వారీగా చూడండి',
  allProducts: 'అన్ని ఉత్పత్తులు',
  supplier: 'సరఫరాదారు',
  note: 'గమనిక',
  feed: 'మేత',
  medicine: 'మందు',
  equipment: 'పరికరాలు',
  goat: 'మేక',
  sheep: 'గొర్రె',
  chicken: 'కోడి',
  hen: 'పెట్ట కోడి',
  sold: 'అమ్మబడింది',
  dead: 'చనిపోయింది',
  breed: 'జాతి',
  age: 'వయసు',
  weight: 'బరువు',
  sortOrder: 'క్రమం',
  emoji: 'ఎమోజీ',
  parentCategory: 'తల్లి వర్గం',
  subcategories: 'ఉప వర్గాలు',
  deleteConfirm: 'మీరు ఖచ్చితంగా తొలగించాలనుకుంటున్నారా?',
  saving: 'సేవ్ అవుతోంది...',
  adding: 'జోడిస్తోంది...',
  updating: 'అప్‌డేట్ అవుతోంది...',
  deleting: 'తొలగిస్తోంది...',
  success: 'విజయవంతం!',
  error: 'లోపం',
  required: 'తప్పనిసరి',
  optional: 'ఐచ్ఛికం',
  rs: 'రూ.',
  per: '/',
  pieces: 'ముక్కలు',
  kg: 'కేజీ',
  // Health
  healthRecords: 'ఆరోగ్య రికార్డులు',
  addHealthRecord: 'ఆరోగ్య రికార్డు జోడించు',
  vaccination: 'టీకా',
  deworming: 'పురుగుమందు',
  vetVisit: 'వెట్ సందర్శన',
  treatment: 'చికిత్స',
  medicine: 'మందు',
  dose: 'మోతాదు',
  nextDue: 'తదుపరి తేదీ',
  noHealthRecords: 'ఆరోగ్య రికార్డులు లేవు',
  upcomingDue: 'రాబోయే తేదీలు',
  // Weight
  weightLog: 'బరువు లాగ్',
  addWeight: 'బరువు జోడించు',
  weightHistory: 'బరువు చరిత్ర',
  currentWeight: 'ప్రస్తుత బరువు',
  // Breeding
  breeding: 'సంతానోత్పత్తి',
  breedingRecord: 'సంతానోత్పత్తి రికార్డు',
  addBreeding: 'రికార్డు జోడించు',
  pregnant: 'గర్భిణి',
  delivered: 'ప్రసవించింది',
  matingDate: 'సంయోగ తేదీ',
  expectedDue: 'అంచనా తేదీ',
  actualDue: 'అసలు తేదీ',
  litterCount: 'పిల్లల సంఖ్య',
  maleName: 'మగ పేరు',
  // Expenses
  expenses: 'ఖర్చులు',
  addExpense: 'ఖర్చు జోడించు',
  totalExpenses: 'మొత్తం ఖర్చులు',
  labour: 'కూలి',
  transport: 'రవాణా',
  other: 'ఇతరత్రా',
  paidTo: 'చెల్లించిన వ్యక్తి',
  netProfit: 'నికర లాభం',
  // Tasks
  tasks: 'పనులు',
  addTask: 'పని జోడించు',
  myTasks: 'నా పనులు',
  assignTo: 'ఎవరికి అప్పగించు',
  dueDate: 'గడువు తేదీ',
  priority: 'ప్రాధాన్యత',
  high: 'అధిక',
  normal: 'సాధారణ',
  low: 'తక్కువ',
  inProgress: 'జరుగుతోంది',
  done: 'పూర్తి',
  noTasks: 'పనులు లేవు',
  // Attendance
  attendance: 'హాజరు',
  markAttendance: 'హాజరు గుర్తించు',
  present: 'హాజరు',
  absent: 'గైర్హాజరు',
  halfDay: 'సగం రోజు',
  leave: 'సెలవు',
  // Reports
  reports: 'నివేదికలు',
  revenue: 'ఆదాయం',
  profit: 'లాభం',
  thisMonth: 'ఈ నెల',
  thisWeek: 'ఈ వారం',
  thisYear: 'ఈ సంవత్సరం',
  topProducts: 'అగ్ర ఉత్పత్తులు',
  expenseBreakdown: 'ఖర్చుల వివరాలు',
  // Catalog order form
  orderOnline: 'ఆన్‌లైన్‌లో ఆర్డర్ చేయండి',
  yourName: 'మీ పేరు',
  yourPhone: 'మీ ఫోన్',
  placeOrder: 'ఆర్డర్ ఇవ్వండి',
  orderPlaced: 'ఆర్డర్ నమోదైంది!',
  // Customer khata
  khata: 'ఖాతా',
  totalDue: 'మొత్తం బాకీ',
  allPaid: 'అన్నీ చెల్లించారు',
  // Delivery
  delivery: 'డెలివరీ',
  deliveryPartners: 'డెలివరీ భాగస్వాములు',
  shipments: 'షిప్మెంట్లు',
  addShipment: 'షిప్మెంట్ సృష్టించు',
  addPartner: 'భాగస్వామి జోడించు',
  trackingCode: 'ట్రాకింగ్ కోడ్',
  deliveryAddress: 'డెలివరీ చిరునామా',
  pincode: 'పిన్‌కోడ్',
  estimatedDelivery: 'అంచనా వేసిన డెలివరీ',
  assignPartner: 'భాగస్వామిని నియమించు',
  codAmount: 'COD మొత్తం',
  codCollected: 'COD వసూలు చేయబడింది',
  paymentType: 'చెల్లింపు రకం',
  vehicle: 'వాహనం',
  areas: 'సేవా ప్రాంతాలు',
  preparing: 'సిద్ధం చేస్తోంది',
  dispatched: 'పంపబడింది',
  outForDelivery: 'డెలివరీలో ఉంది',
  failed: 'విఫలమైంది',
  returned: 'తిరిగి వచ్చింది',
  noShipments: 'షిప్మెంట్లు లేవు',
  noPartners: 'డెలివరీ భాగస్వాములు లేరు',
  markDelivered: 'డెలివరీ అయినట్లు గుర్తించు',
  markDispatched: 'పంపినట్లు గుర్తించు',
  collectCod: 'COD వసూలు చేయి',
  whatsappTrack: 'ట్రాకింగ్ పంచుకో',
  customerPortal: 'కస్టమర్ పోర్టల్',
  settings: 'సెట్టింగ్స్',
}

// ── English translations ──────────────────────────────────────────────────────
const en = {
  appName: 'KRUTHIK FARM',
  tagline: 'Farm Fresh • Direct to You',
  loading: 'Loading...',
  login: 'Login',
  logout: 'Logout',
  phone: 'Phone Number',
  password: 'Password',
  loginBtn: 'Login',
  loggingIn: 'Logging in...',
  dashboard: 'Dashboard',
  products: 'Products',
  animals: 'Animals',
  orders: 'Orders',
  customers: 'Customers',
  employees: 'Employees',
  inventory: 'Inventory',
  categories: 'Categories',
  catalog: 'Catalog',
  publicCatalog: 'Public Catalog',
  search: 'Search...',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  close: 'Close',
  back: '← Back',
  name: 'Name',
  nameTelugu: 'Name (Telugu)',
  price: 'Price',
  stock: 'Stock',
  minStock: 'Min Stock',
  unit: 'Unit',
  description: 'Description',
  category: 'Category',
  subcategory: 'Subcategory',
  photo: 'Photo',
  status: 'Status',
  available: 'Available',
  unavailable: 'Unavailable',
  totalProducts: 'Total Products',
  availableProducts: 'Available Products',
  totalOrders: 'Total Orders',
  completedOrders: 'Completed Orders',
  totalCustomers: 'Total Customers',
  totalEmployees: 'Total Employees',
  inventoryValue: 'Inventory Value',
  totalRevenue: 'Total Revenue',
  pendingPayments: 'Pending Payments',
  recentOrders: 'Recent Orders',
  lowStock: 'Low Stock',
  quickActions: 'Quick Actions',
  farmSummary: 'Farm Summary',
  pending: 'Pending',
  confirmed: 'Confirmed',
  completed: 'Completed',
  cancelled: 'Cancelled',
  all: 'All',
  noProducts: 'No products yet',
  noOrders: 'No orders yet',
  noCustomers: 'No customers yet',
  noAnimals: 'No animals yet',
  addProduct: 'Add Product',
  editProduct: 'Edit Product',
  deleteProduct: 'Delete Product',
  addCategory: 'Add Category',
  addEmployee: 'Add Employee',
  addCustomer: 'Add Customer',
  addAnimal: 'Add Animal',
  addOrder: 'Add Order',
  totalAmount: 'Total Amount',
  paidAmount: 'Paid Amount',
  balance: 'Balance Due',
  customer: 'Customer',
  product: 'Product',
  quantity: 'Quantity',
  address: 'Address',
  role: 'Role',
  owner: 'Owner',
  manager: 'Manager',
  employee: 'Employee',
  welcome: 'Welcome',
  callUs: 'Call Us',
  whatsapp: 'Order on WhatsApp',
  contactUs: 'Contact Us',
  shopByCategory: 'Shop by Category',
  allProducts: 'All Products',
  supplier: 'Supplier',
  note: 'Note',
  feed: 'Feed',
  medicine: 'Medicine',
  equipment: 'Equipment',
  goat: 'Goat',
  sheep: 'Sheep',
  chicken: 'Chicken',
  hen: 'Hen',
  sold: 'Sold',
  dead: 'Dead',
  breed: 'Breed',
  age: 'Age',
  weight: 'Weight (kg)',
  sortOrder: 'Sort Order',
  emoji: 'Emoji',
  parentCategory: 'Parent Category',
  subcategories: 'Subcategories',
  deleteConfirm: 'Are you sure you want to delete this?',
  saving: 'Saving...',
  adding: 'Adding...',
  updating: 'Updating...',
  deleting: 'Deleting...',
  success: 'Success!',
  error: 'Error',
  required: 'Required',
  optional: 'Optional',
  rs: 'Rs.',
  per: '/',
  pieces: 'pieces',
  kg: 'kg',
  // Health
  healthRecords: 'Health Records',
  addHealthRecord: 'Add Health Record',
  vaccination: 'Vaccination',
  deworming: 'Deworming',
  vetVisit: 'Vet Visit',
  treatment: 'Treatment',
  medicine: 'Medicine',
  dose: 'Dose',
  nextDue: 'Next Due Date',
  noHealthRecords: 'No health records yet',
  upcomingDue: 'Upcoming Due',
  // Weight
  weightLog: 'Weight Log',
  addWeight: 'Log Weight',
  weightHistory: 'Weight History',
  currentWeight: 'Current Weight',
  // Breeding
  breeding: 'Breeding',
  breedingRecord: 'Breeding Record',
  addBreeding: 'Add Record',
  pregnant: 'Pregnant',
  delivered: 'Delivered',
  matingDate: 'Mating Date',
  expectedDue: 'Expected Due',
  actualDue: 'Actual Due',
  litterCount: 'Litter Count',
  maleName: 'Male Name',
  // Expenses
  expenses: 'Expenses',
  addExpense: 'Add Expense',
  totalExpenses: 'Total Expenses',
  labour: 'Labour',
  transport: 'Transport',
  other: 'Other',
  paidTo: 'Paid To',
  netProfit: 'Net Profit',
  // Tasks
  tasks: 'Tasks',
  addTask: 'Add Task',
  myTasks: 'My Tasks',
  assignTo: 'Assign To',
  dueDate: 'Due Date',
  priority: 'Priority',
  high: 'High',
  normal: 'Normal',
  low: 'Low',
  inProgress: 'In Progress',
  done: 'Done',
  noTasks: 'No tasks yet',
  // Attendance
  attendance: 'Attendance',
  markAttendance: 'Mark Attendance',
  present: 'Present',
  absent: 'Absent',
  halfDay: 'Half Day',
  leave: 'Leave',
  // Reports
  reports: 'Reports & Analytics',
  revenue: 'Revenue',
  profit: 'Profit',
  thisMonth: 'This Month',
  thisWeek: 'This Week',
  thisYear: 'This Year',
  topProducts: 'Top Products',
  expenseBreakdown: 'Expense Breakdown',
  // Catalog order form
  orderOnline: 'Order Online',
  yourName: 'Your Name',
  yourPhone: 'Your Phone',
  placeOrder: 'Place Order',
  orderPlaced: 'Order Placed!',
  // Customer khata
  khata: 'Khata (Credit)',
  totalDue: 'Total Due',
  allPaid: 'All Paid',
  // Delivery
  delivery: 'Delivery',
  deliveryPartners: 'Delivery Partners',
  shipments: 'Shipments',
  addShipment: 'Create Shipment',
  addPartner: 'Add Partner',
  trackingCode: 'Tracking Code',
  deliveryAddress: 'Delivery Address',
  pincode: 'Pincode',
  estimatedDelivery: 'Est. Delivery',
  assignPartner: 'Assign Partner',
  codAmount: 'COD Amount',
  codCollected: 'COD Collected',
  paymentType: 'Payment',
  vehicle: 'Vehicle',
  areas: 'Service Areas',
  preparing: 'Preparing',
  dispatched: 'Dispatched',
  outForDelivery: 'Out for Delivery',
  failed: 'Failed',
  returned: 'Returned',
  noShipments: 'No shipments yet',
  noPartners: 'No delivery partners yet',
  markDelivered: 'Mark Delivered',
  markDispatched: 'Mark Dispatched',
  collectCod: 'Collect COD',
  whatsappTrack: 'Share Tracking',
  customerPortal: 'Customer Portal',
  settings: 'Settings',
}

const strings = { en, te }

// ── Context ───────────────────────────────────────────────────────────────────
const LangContext = createContext({ lang: 'en', t: en, toggleLang: () => {} })

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('lang')
    if (saved === 'te' || saved === 'en') setLang(saved)
  }, [])

  const toggleLang = () => {
    const next = lang === 'en' ? 'te' : 'en'
    setLang(next)
    localStorage.setItem('lang', next)
  }

  return (
    <LangContext.Provider value={{ lang, t: strings[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
